# Generated by Django 5.2.6 on 2025-09-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_projeto_criado_por_remove_projeto_nome_and_more'),
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minhas_tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('a_fazer', 'A Fazer'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='a_fazer', max_length=20, verbose_name='Status'),
        ),
    ]
