# Generated by Django 5.2.6 on 2025-09-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='nome',
        ),
        migrations.AddField(
            model_name='projeto',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participacao_projetos', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
